### Separate Name, Contact and MailId from the given DataFrame.

In [56]:
import pandas as pd

In [57]:
data = ["kumod1234287423@gmail.com","hema@7654874537gmail.com","ra9637452637hul@gmail.com","rupanshi@yahoo.com8347658382",
        "deepanshu345@gmail.com","387@gmail9567848567.com","shashank786@gmail.com","7698457382kirti456@gmail.com",
        "prince34@ymail.com","bhanu@9456738454gmail.com","ANKiT@8576893945gmail.com","mo56@gmail.com","345@gmail.com",
        "LaXMi456@gmail.com","567@yahoo.com","abhi345nash@ymail.com","komal@34gmail7896453678.com","deepak@345gmail.com",
        "345@yahoo.com","manu9845673245@ymail.com"]

df = pd.DataFrame({"Details":data})

### Showing Data

In [58]:
df

                         Details
0      kumod1234287423@gmail.com
1       hema@7654874537gmail.com
2      ra9637452637hul@gmail.com
3   rupanshi@yahoo.com8347658382
4         deepanshu345@gmail.com
5        387@gmail9567848567.com
6          shashank786@gmail.com
7   7698457382kirti456@gmail.com
8             prince34@ymail.com
9      bhanu@9456738454gmail.com
10     ANKiT@8576893945gmail.com
11                mo56@gmail.com
12                 345@gmail.com
13            LaXMi456@gmail.com
14                 567@yahoo.com
15         abhi345nash@ymail.com
16   komal@34gmail7896453678.com
17           deepak@345gmail.com
18                 345@yahoo.com
19      manu9845673245@ymail.com

### Separating Contact Using Details Given in DataFrame.

In [59]:
contact = []

for i in df["Details"]:

    x = i
    for j in range(len(i)):
        if i[j].isalpha():
            x = x.replace(i[j],",")
            
    x = x.replace("@","")
    x = x.replace(".","")
    y = x.split(",")
    z = sorted(y,reverse=True)
    #print(z)
    
    for i in z:
        if len(i)==10:
            if (i[0]=="9") or (i[0]=="8") or (i[0]=="7"):
                #print(i)
                contact.append(i)
                break
            else:
                #print("No Contact")
                contact.append("No Contact")
                break
        else:
            #print("No Contact")
            contact.append("No Contact")
            break

In [60]:
#print(contact)

### Adding Contact Column in The Datafreame.

In [61]:
df["Contact"] = contact

In [62]:
df

                         Details     Contact
0      kumod1234287423@gmail.com  No Contact
1       hema@7654874537gmail.com  7654874537
2      ra9637452637hul@gmail.com  9637452637
3   rupanshi@yahoo.com8347658382  8347658382
4         deepanshu345@gmail.com  No Contact
5        387@gmail9567848567.com  9567848567
6          shashank786@gmail.com  No Contact
7   7698457382kirti456@gmail.com  7698457382
8             prince34@ymail.com  No Contact
9      bhanu@9456738454gmail.com  9456738454
10     ANKiT@8576893945gmail.com  8576893945
11                mo56@gmail.com  No Contact
12                 345@gmail.com  No Contact
13            LaXMi456@gmail.com  No Contact
14                 567@yahoo.com  No Contact
15         abhi345nash@ymail.com  No Contact
16   komal@34gmail7896453678.com  7896453678
17           deepak@345gmail.com  No Contact
18                 345@yahoo.com  No Contact
19      manu9845673245@ymail.com  9845673245

In [63]:
mail = []

for i in df["Details"]:
    for j in df["Contact"]:
        if j in i:
            i = i.replace(j,"")
            mail.append(i)
    if i not in mail:   
        mail.append(i)

In [64]:
#print(mail)

In [65]:
df["Mail Id"] = mail

In [66]:
df

                         Details     Contact                    Mail Id
0      kumod1234287423@gmail.com  No Contact  kumod1234287423@gmail.com
1       hema@7654874537gmail.com  7654874537             hema@gmail.com
2      ra9637452637hul@gmail.com  9637452637            rahul@gmail.com
3   rupanshi@yahoo.com8347658382  8347658382         rupanshi@yahoo.com
4         deepanshu345@gmail.com  No Contact     deepanshu345@gmail.com
5        387@gmail9567848567.com  9567848567              387@gmail.com
6          shashank786@gmail.com  No Contact      shashank786@gmail.com
7   7698457382kirti456@gmail.com  7698457382         kirti456@gmail.com
8             prince34@ymail.com  No Contact         prince34@ymail.com
9      bhanu@9456738454gmail.com  9456738454            bhanu@gmail.com
10     ANKiT@8576893945gmail.com  8576893945            ANKiT@gmail.com
11                mo56@gmail.com  No Contact             mo56@gmail.com
12                 345@gmail.com  No Contact              345@gmail.com
13            LaXMi456@gmail.com  No Contact         LaXMi456@gmail.com
14                 567@yahoo.com  No Contact              567@yahoo.com
15         abhi345nash@ymail.com  No Contact      abhi345nash@ymail.com
16   komal@34gmail7896453678.com  7896453678          komal@34gmail.com
17           deepak@345gmail.com  No Contact        deepak@345gmail.com
18                 345@yahoo.com  No Contact              345@yahoo.com
19      manu9845673245@ymail.com  9845673245             manu@ymail.com

In [67]:
name = []

for i in df["Mail Id"]:
    a = i.split("@")
    b = a[0]
    
    for j in b:
        if j.isdigit():
            b = b.replace(j,"")
    if len(b)>1:
        name.append(b.title())
    else:
        name.append("No Name")

In [68]:
#print(name)

In [69]:
df.insert(1,"Name",name)

In [70]:
df

,Details,Name,Contact,Mail Id
0,kumod1234287423@gmail.com,Kumod,No Contact,kumod1234287423@gmail.com
1,hema@7654874537gmail.com,Hema,7654874537,hema@gmail.com
2,ra9637452637hul@gmail.com,Rahul,9637452637,rahul@gmail.com
3,rupanshi@yahoo.com8347658382,Rupanshi,8347658382,rupanshi@yahoo.com
4,deepanshu345@gmail.com,Deepanshu,No Contact,deepanshu345@gmail.com
5,387@gmail9567848567.com,No Name,9567848567,387@gmail.com
6,shashank786@gmail.com,Shashank,No Contact,shashank786@gmail.com
7,7698457382kirti456@gmail.com,Kirti,7698457382,kirti456@gmail.com
8,prince34@ymail.com,Prince,No Contact,prince34@ymail.com
9,bhanu@9456738454gmail.com,Bhanu,9456738454,bhanu@gmail.com
10,ANKiT@8576893945gmail.com,Ankit,8576893945,ANKiT@gmail.com
11,mo56@gmail.com,Mo,No Contact,mo56@gmail.com
12,345@gmail.com,No Name,No Contact,345@gmail.com
13,LaXMi456@gmail.com,Laxmi,No Contact,LaXMi456@gmail.com
14,567@yahoo.com,No Name,No Contact,567@yahoo.com
15,abhi345nash@ymail.com,Abhinash,No Contact,abhi345nash@ymail.com
16,komal@34gmail7896453678.com,Komal,7896453678,komal@34gmail.com
17,deepak@345gmail.com,Deepak,No Contact,deepak@345gmail.com
18,345@yahoo.com,No Name,No Contact,345@yahoo.com
19,manu9845673245@ymail.com,Manu,9845673245,manu@ymail.com